app = "taiwan-culture-event-info"
primary_region = "hkg"

[build]
  dockerfile = "deployment_tcei/Dockerfile"

[env]
  DEBUG = "False"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "sqlite_data"
  destination = "/web/db"