name: Deploy Django to Fly.io

on:
  push:
    branches:
      - github_ci_250318

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Add Fly to PATH
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Verify Fly CLI installation
        run: $HOME/.fly/bin/flyctl version

      - name: Run Django Tests
        run: |
            source venv/bin/activate
            python manage.py test

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export FLYCTL_ACCESS_TOKEN=$FLY_API_TOKEN
          $HOME/.fly/bin/flyctl deploy --remote-only --yes