name: Deploy Django to Fly.io

on:
  push:
    branches:
      - github_ci_250318

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Flyio - Install Flyio
        run: curl -L https://fly.io/install.sh | sh

      - name: Flyio - Add Flyio github path
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Flyio - Verify Flyio installation
        run: $HOME/.fly/bin/flyctl version

      - name: Running Test - Setup DockerEnv
        uses: docker/setup-buildx-action@v2

      - name: Running Test - Setup DockerEnv
        run: make run-prod

      - name: Running Test
        run: python manage.py test

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export FLYCTL_ACCESS_TOKEN=$FLY_API_TOKEN
          $HOME/.fly/bin/flyctl deploy --remote-only --yes